updated file

diff --git a/.ci/azure-pipelines-test-template.yml b/.ci/azure-pipelines-test-template.yml
--- a/.ci/azure-pipelines-test-template.yml
+++ b/.ci/azure-pipelines-test-template.yml
@@ -36,9 +36,11 @@ jobs:
             echo "Contents of System.DefaultWorkingDirectory:"
             find $(System.DefaultWorkingDirectory) -type f -name "*.xml" 2>/dev/null | head -20
             echo "---"
-            ls -la $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/ 2>/dev/null || echo "Directory not found"
+            ls -lFa $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/ 2>/dev/null || echo "Directory not found"
             echo "---"
-            ls -la $(System.DefaultWorkingDirectory)/ 2>/dev/null
+            ls -lFa $(System.DefaultWorkingDirectory)/ 2>/dev/null
+            echo "---"
+            ls -lFa $(System.DefaultWorkingDirectory)/build/$(cmake.preset)/tests 2>/dev/null || echo "tests Directory not found"
         condition: eq(variables['Agent.OS'], 'Linux')
 
       - task: PowerShell@2
